# Generated by Django 3.1.2 on 2020-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_markattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markattendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markattendance',
            name='time',
        ),
        migrations.AddField(
            model_name='markattendance',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
